### ISSUE TITLE
Remove ConorMacBride/install-package dependency?

### ISSUE THREAD

**Issue by mfinelli** [SanderVocke/setup-qemu-container#11]
Would you accept a pull request to remove the `ConorMacBride/install-package` dependency? This action doesn't appear to support macos or windows anyway so we can just call `apt-get` directly without needing to rely on another action that could silently change in the future.

**Comment by SanderVocke** [comment]
Hi Mario,

Good idea, I would accept a PR for that. Thanks!

**Comment by SanderVocke** [comment]
P.S.: Your other PR was just merged. If you intend to make the PR you suggested here soon, I can merge it and then release both of your changes to the Marketplace version.

**Comment by SanderVocke** [comment]
I just created a v1.1.8 release with your changes and updated the "v1" and "v1.1" tags. Thanks again!
